### ISSUE TITLE
Copy config issue

### ISSUE THREAD

**Issue by raisonon** [cnj-digital/seotamic#1]
Got asset container error as my asset container was named images.

Tried

```
php artisan vendor:publish --provider="cnj/seotamic" --tag=config
Unable to locate publishable resources.
Publishing complete.
```

In the end just copied the file manually into config directory to fix, but thought should flag up this problem. Thanks for the great SEO addon!

**Comment by martink635** [comment]
Thanks for the report, the README was wrong, fixed in the latest commit
