### ISSUE TITLE
Error: Signature is missing  (for og:image)

### ISSUE THREAD

**Issue by connor11528** [cnj-digital/seotamic#15]
Hi there, I am using this plug in populate images. It's working great on the backend but when it injects the `og:image` tag it links to an image path that does not exist.

<img width="652" alt="Screen Shot 2021-09-11 at 10 23 29 PM" src="https://user-images.githubusercontent.com/3578908/132973248-52298c2e-1d81-48ba-8881-ba04c633ab32.png">

Following that URL I get an error: Impossible to create the root directory "/var/www/html/storage/statamic/glide/containers/images/terminator-ai.jpeg".

<img width="1037" alt="Screen Shot 2021-09-11 at 10 23 48 PM" src="https://user-images.githubusercontent.com/3578908/132973253-e2dfb980-ede2-41f5-8614-d4ec9db8632c.png">

Is there a way I can configure the path so that the og:image links to a real image instead of trying to create a directory?

The image is looking fine on the Statamic backend :) 

<img width="875" alt="Screen Shot 2021-09-11 at 10 24 58 PM" src="https://user-images.githubusercontent.com/3578908/132973283-3ebdcb2b-03d6-4e6c-8a25-550f7d7308ac.png">

This is an example of a [live post](https://www.employbl.com/blog/artificial-intelligence-companies-and-startups) that it's happening for.

This is the path to the actual image I'd like to use: https://www.employbl.com/assets/terminator-ai.jpeg

If I change the seotamic config to `'container' => 'assets',` then no image shows up in the og:image tag.

**Comment by connor11528** [comment]
I was able to get around this issue by giving permissions to the directories. However now I am getting a new error: “signature is missing”

![F228FED5-D875-4E1C-AFA9-C90795C409F1](https://user-images.githubusercontent.com/3578908/134934924-587b238b-b937-46d5-b0bf-121dbc0edbce.png)

**Comment by martink635** [comment]
I did a couple of tests and can't reproduce this. We are using Glide to manipulate the image size and quality (the values are hardcoded).

You need to have glide working by setting u gd/imagick correctly in the Statamic assets.php config file. Currently, there is no option to turn this off, but it's something we might add.

**Comment by connor11528** [comment]
Okay gotcha. I will look into configuring glide for my site..
