### ISSUE TITLE
Empty tags when using Blade

### ISSUE THREAD

**Issue by stuartcusackie** [cnj-digital/seotamic#17]
Not sure if you are planning to support Blade but I just tried it out in my Blade layouts and there's no data.

![image](https://user-images.githubusercontent.com/20210934/134808681-8e18a76e-33cc-49da-a1a3-6bb2c57ce193.png)

![image](https://user-images.githubusercontent.com/20210934/134808689-dccbabb5-3b10-46a6-8b79-ca2be97307e7.png)

**Comment by lokmanm** [comment]
Is there any guide on how to support Blade with Statamic ? I would gladly push a PR

**Comment by stuartcusackie** [comment]
@lokmanm I'm afraid not! My experience with Statammic blade has mostly been trial and error.

The seopro addon had a similar problem:
https://github.com/statamic/seo-pro/issues/173

I've had to go with a custom SEO field implementation for now. I'm afraid I won't have time for a PR.

**Comment by martink635** [comment]
Blade output works fine in version 3, possibly v2 as well… 

More here: https://github.com/cnj-digital/seotamic#blade
