### ISSUE TITLE
Custom title / description not outputting

### ISSUE THREAD

**Issue by jeremydouglas** [cnj-digital/seotamic#2]
When using the `Custom Meta Title` and other custom fields, they are not outputting to the html template.

I think this started happening on Statamic 3 Beta 32.

Thanks, I really appreciate you putting this add-on out while we wait for the official ones!

**Comment by martink635** [comment]
Thanks for reporting this, I've just checked and it seems to get the value from the context fields I need to do `->value()->value()` which seems like it was changed 🙂

Will fix it probably tomorrow

**Comment by jeremydouglas** [comment]
Thanks Martin!

**Comment by martink635** [comment]
Pushed a fix, should be fine now :)
