### ISSUE TITLE
"unlicensed" message under 2.1.0

### ISSUE THREAD

**Issue by alexandergknoll** [cnj-digital/seotamic#24]
When using 2.1.0 of this add-on, Statamic lists it as "unlicensed" and warns that "This site is using commercial addons. Please purchase appropriate licenses."  Based on the readme, it sounds like 2.1.0 should be MIT licensed and not require the purchase of a commercial license to use in production.  Would you be able to confirm?

![image](https://user-images.githubusercontent.com/9630849/202555518-ebd29771-70f8-442d-a163-7c4cc1a35522.png)

**Comment by martink635** [comment]
Hello Alex, 
MIT does not mean it can't be sold.
