### ISSUE TITLE
v3 Installation Failure

### ISSUE THREAD

**Issue by heywhy** [cnj-digital/seotamic#34]
I'm unable to install the v3 successfully, see the error below:

<img width="1116" alt="Screenshot 2023-03-06 at 15 45 59" src="https://user-images.githubusercontent.com/13123868/223146960-9ebb9b8f-a32f-4784-9f66-14c1d96e16e2.png">

After inspecting the source code I found out that the service provider is using the `boot` method instead of the `bootAddon`. Please fix it ASAP, thank you.

**References**:

https://statamic.dev/extending/addons#creating-an-addon
https://github.com/cnj-digital/seotamic/blob/master/src/ServiceProvider.php#L45

**Comment by heywhy** [comment]
@martink635 I've created a PR (#35)  to apply the fix as suggested above. Please review and make a new release.

**Comment by martink635** [comment]
Merged, thanks!
