### ISSUE TITLE
Migration v2 to v3 fails

### ISSUE THREAD

**Issue by mathamel** [cnj-digital/seotamic#36]
Hi, trying to update from v2 to v3, but it fails

$ php artisan seotamic:migrate
Migrating SEOtamic data from v2 to v3

Make sure you have a backup of your data before you continue!

 Do you want to continue? (yes/no) [yes]:
 > yes

1. Migrating blueprints…

   RuntimeException 

  Statamic\Eloquent\Fields\Exception

  at vendor/laravel/framework/src/Illuminate/Support/helpers.php:330
    326▕             if (is_string($exception) && class_exists($exception)) {
    327▕                 $exception = new $exception(...$parameters);
    328▕             }
    329▕ 
  ➜ 330▕             throw is_string($exception) ? new RuntimeException($exception) : $exception;
    331▕         }
    332▕ 
    333▕         return $condition;
    334▕     }

      +12 vendor frames 
  13  [internal]:0
      Cnj\Seotamic\Commands\MigrateCommand::Cnj\Seotamic\Commands\{closure}(Object(Statamic\Eloquent\Collections\Collection))

      +17 vendor frames 
  31  artisan:35
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
$

**Comment by martink635** [comment]
Thanks for reporting this? Are you able to share the repo with me, so I can take a look?

Thanks!

**Comment by martink635** [comment]
Hello, since you did not provide any updates in the past month I will be closing this issue. If it still persists open a new one with more information. Thanks!
