### ISSUE TITLE
Use storage API instead of relative asset paths

### ISSUE THREAD

**Issue by arcs-** [cnj-digital/seotamic#41]
Seotamic currently uses relative asset paths, this does not work well with the filesystem Statamic uses. While it is already not recommended to concatenate the path of assets within the frontend, this approach breaks entirely if assets are on a different Server (e.g. on a S3 driver).

So instead of using `url($asset);` with should use `Storage::disk(config('seotamic.container'))->url($asset);`. I made this as a draft here: https://github.com/arcs-/seotamic/tree/storage-api, however, I'm myself not well versed on this. Could someone look further into this?

**Comment by martink635** [comment]
Thanks for raising this issue, will tackle it in the next release!
