### ISSUE TITLE
Title tag not being populated since update

### ISSUE THREAD

**Issue by andylarkum** [cnj-digital/seotamic#42]
...have I missed a step?

All title tags are now empty and are not being repopulated - but they have been set.

Theme template has:
`{{ seotamic }}`

    <link rel="stylesheet" href="{{ mix src='css/tailwind.css' }}">

Rendered content has:
`<title></title>
<meta name="description" content=""><link rel="stylesheet" href="[/css/tailwind.css?id=1d35895506f4ec8afc966b015ea429e7](http://localhost:8000/css/tailwind.css?id=1d35895506f4ec8afc966b015ea429e7)">`

**Comment by martink635** [comment]
Thanks for reporting this. I need some more information on the issue, since I can't reproduce it. If the repo is open or you are able to share it, feel free to send an invite for me and I can take a look.

**Comment by andylarkum** [comment]
Hi
I've added you to the repo
Thanks!
A.

**Comment by andylarkum** [comment]
Hi @martink635 
Any joy on this?

**Comment by martink635** [comment]
Hey, I've checked it out and it seems the migration script was not working properly on your use case. I've modified the migration script and pushed the new version. 

Update Seotamic to 3.0.9 and retry running the migration script `php artisan seotamic:migrate`

Now it should prompt you to update 2 blueprints (posts and pages) and the output will work fine :)

**Comment by andylarkum** [comment]
Fixed! Thanks so much :)

A.
