### ISSUE TITLE
Statamic 4 upgrade issue

### ISSUE THREAD

**Issue by jasonbradberry** [cnj-digital/seotamic#49]
I'm getting a compatibility issue when trying to update from Statamic V3 to V4. Is v3.0.9 compatible with Statamic 4?

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires cnj/seotamic 3.0.9 -> satisfiable by cnj/seotamic[v3.0.9].
    - cnj/seotamic v3.0.9 requires statamic/cms ^3.3.0 -> found statamic/cms[v3.3.0-beta.1, ..., 3.4.x-dev] but it conflicts with your root composer.json require (^4.1).
```

**Comment by martink635** [comment]
Hello, it is not, please use the latest beta release https://github.com/cnj-digital/seotamic/releases/tag/v4.0.0-beta.1

the 4.*.* is compatible with Statamic 4, read more here: https://github.com/cnj-digital/seotamic#version-4-changes
