### ISSUE TITLE
Unable to access after getting pro

### ISSUE THREAD

**Issue by senyil** [cnj-digital/seotamic#54]
Visiting plugin page on CP results this error;
Cnj\Seotamic\FieldTypes\SeotamicSocialPreview::getImageUrl(): Return value must be of type string, null returned

'cnj/seotamic' => 'pro', added.

**Comment by martink635** [comment]
Sorry for getting back so late on this.

Can you share some reproduction steps or the website you are having issues with this? Feel free to email it a martin@cnj.si
