### ISSUE TITLE
Migration error

### ISSUE THREAD

**Issue by zsoltjanes** [cnj-digital/seotamic#61]
Hi!

I use "statamic/cms": "^4.0", with  "cnj/seotamic": "^4.0", but i had v2 version about your addon before. I wanted to upgrade and I faced with an error:  `Call to undefined method Statamic\Fields\Blueprint::hasSection()`

I started debugging and it looks like in statamic v4 this method is removed. There are new methods instead of `hasSection()` becomes to `hasTab()` and `removeSection()` becomes `removeTab()`. Please take a look about it!

**Comment by martink635** [comment]
Hello,

If I understand correctly you've tried to upgrade from a v2 Seotamic to v4? 

Did you follow the upgrade path described [here](https://github.com/cnj-digital/seotamic?tab=readme-ov-file#migration-from-version-2)?

**Comment by zsoltjanes** [comment]
Yes, I updated Statamic from v3 to v4 and after that, I wanted to upgrade the addons. Since in statamic 4 does not have hasSection() method I faced this error.

You can reproduce this if you install Statamic 3 after that your addon v2 version, after that upgrade statamic to v4, and after that upgrade your addon.

**Comment by martink635** [comment]
Ahh I understand. If you had a Statamic v3 version, you first had to update to Seotamic v3, before making the update to Statamic 4. 

Is this an option for you? The upgrade script works only on Statamic v3, that is correct.
Can you revert back and do the upgrade, otherwise feel free to suggest open a PR or suggest a way to make this happen.

**Comment by zsoltjanes** [comment]
Something like this is what I suggest:

```
        $blueprintsWithSeotamicFields = $blueprints->filter(function ($blueprint) {
            if(method_exists($blueprint, 'hasSection')) {
                return $blueprint->hasSection('SEO') || $blueprint->hasSection('Social');
            }
            
            if(method_exists($blueprint, 'hasTab')) {
                return $blueprint->hasTab('SEO') || $blueprint->hasTab('Social');
            }
        });
```

**Comment by martink635** [comment]
Great, I've opened a PR https://github.com/cnj-digital/seotamic/pull/65 can you test it if everything works, since I do not have a Statamic 3 setup anymore…

**Comment by zsoltjanes** [comment]
Please do the same with the removeSection part in statamic 4 it is removeTab

**Comment by martink635** [comment]
Done, please test again

**Comment by zsoltjanes** [comment]
yes its fine

**Comment by zsoltjanes** [comment]
thx
