### ISSUE TITLE
Pagespeed insight URL null

### ISSUE THREAD

**Issue by mathamel** [cnj-digital/seotamic#68]
We updated to v4, now all content Pagespeed insight URL are null

https://null
My Awesome SEO Title

Please advise how to fix this.

**Comment by martink635** [comment]
Hello,
are you on the latest version? I am not sure what's wrong I've checked on several of our sites and its working fine.
Would you be comfortable sharing the repo with me so I can take a look?

**Comment by mathamel** [comment]
Yes I can share the repo, on bitbucket, I will add your email, how can you share it to me?

**Comment by martink635** [comment]
Great, invite martin@cnj.si 🙂

**Comment by martink635** [comment]
@mathamel  Can you please send some content as well? Thanks!

**Comment by mathamel** [comment]
Here's some content



*Mathieu HamelPrésident514-360-0920 poste 101 | manaweb.ca
<http://manaweb.ca>*
<https://www.manaweb.ca/>
*Créativité • Agilité • Transparence *

**Comment by mathamel** [comment]
Resolved, it was a setting (preview url). Thank you for your help.
