### ISSUE TITLE
Titles in YAML

### ISSUE THREAD

**Issue by websmyth** [cnj-digital/seotamic#7]
This might be a misconfiguration on my part, but it _seems_ that if a page has `title` defined in the template/md file, it’s not outputted. 

For instance, a search page in `/resources/views/search.antlers.html`:

```
---
title: 'Search'
---
<main class="container search-page" id="content" role="main">
  <h1>Search</h1>

  {{ partial:search-form }}
  
</main>
```

The `title` isn’t outputted into the `<title>` tag.

**Environment**
Statamic 3.0.30 Pro
Laravel 7.29.2
PHP 7.4.11
cnj/seotamic 2.0.2
statamic/migrator dev-master

**Comment by martink635** [comment]
Thanks for reporting this issue.

We almost never assign variables/values in template/markdown files, so it never occured to us. What would be the desired output for the page title here? Should we do the prepend/append stuff as well?

**Comment by websmyth** [comment]
Perhaps if there isn’t a `title` in the content look for the `title` value in the template, perhaps?

I’d guess prepend/append would be good, too. But that’s just my opinion. 😄

**Comment by martink635** [comment]
@websmyth I will leave this package open, but I couldn't get variables values defined in templates/yaml style in the addon itself. If you have any solution for this we can solve this quickly
