### ISSUE TITLE
No output at all on all pages

### ISSUE THREAD

**Issue by mathamel** [cnj-digital/seotamic#72]
Using the lite version, a website https://nannysecours.com have only empty title tag, no meta description, and no social output.

**Comment by mathamel** [comment]
![image](https://github.com/cnj-digital/seotamic/assets/12539609/48009ccd-19f7-418a-a833-93f06c0ffedf)

**Comment by mathamel** [comment]
Cannot create new Entry

**Comment by mathamel** [comment]
Ok I found out that the error happens because I do have a computed field on this collection, and it failed at this point.

**Comment by martink635** [comment]
@mathamel This should be now fixed, thanks for the report!
